Social_site_project/urls.py
"""Social_site_project URL Configuration
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from App_post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('userApp.urls')),
    path('post/',include('App_post.urls')),
    path('',views.Homepage,name='homepage'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userApp/urls.py
from django.urls import path
from .import views
app_name = 'userApp'
urlpatterns = [
    path('sing_up/',views.Sing_up,name='sing_up'),
    path('login/',views.login_page,name='login'),
    path('Logout/',views.Log_out,name='Logout'),
    path('ProfileEdit/',views.P_Edit_page,name='ProfileEdit'),
    path('profile/',views.view_profile,name='profile'),
    path('s_single_user/<username>/',views.Single_user,name='search_Single_user'),
    path('followed/<username>/',views.follow,name='followed'),
    path('unfollow/<username>/',views.unfollow,name='unfollow'),
]

userApp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=250)
    data_of_birth = models.DateTimeField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

    def __str__(self):
        return self.user.username


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    create_date = models.DateTimeField(auto_now_add=True)

userApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True, label="",
                             widget=forms.TextInput(attrs={'placeholder': 'Email ',
                                                           'type': 'email',
                                                           'class': 'form-control', }))

    # just form design er Jonno . last a widget diye korte partam
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                                                      'class': 'form-control', }))
    password1 = forms.CharField(required=True,
                                label='',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control', }))
    password2 = forms.CharField(required=True,
                                label='',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password confirmation',
                                                                  'class': 'form-control', }))

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class profile_Edit(forms.ModelForm):
    class Meta:
        model = UserProfile()
        exclude = ('user',)

userApp/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, get_object_or_404
from .forms import CreateUserForm, profile_Edit
from .models import UserProfile, Follow
from App_post.forms import PostForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required


# Create your views here.


def Sing_up(request):
    form = CreateUserForm()
    registered = False
    if request.method == 'POST':
        form = CreateUserForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.profile_pic = 'auto_pic_r/default_pic.png'
            user_profile.save()
            return HttpResponseRedirect(reverse('userApp:login'))

    data = {
        "title": "sing_up page",
        "form": form,
    }
    return render(request, 'userApp/Sing_up.html', data)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_post:homepage'))
    data = {
        "title": 'login page',
        "form": form,
    }
    return render(request, 'userApp/login.html', data)


@login_required
def Log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('userApp:login'))


@login_required
def P_Edit_page(request):
    # current_user = request.user  # any one currentUser user korte hobe
    try:
        current_users = UserProfile.objects.get(user=request.user)
    except:
        current_users = get_object_or_404(User, username=request.user)

    form = profile_Edit(instance=current_users)

    if request.method == 'POST':
        form = profile_Edit(request.POST, request.FILES, instance=current_users)
        if form.is_valid():
            form.save(commit=True)
            form = profile_Edit(instance=current_users)
            return HttpResponseRedirect(reverse('userApp:profile'))
    data = {
        "title": 'Edit profile ',
        "form": form,
    }
    return render(request, 'userApp/profile_Edit.html', data)


@login_required
def view_profile(request):
    current_user = request.user
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('App_post:homepage'))

    data = {
        "title": current_user,
        "form": form
    }
    return render(request, 'userApp/profile.html', data)


@login_required
def Single_user(request, username):
    user_single = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user_single)

    if user_single == request.user:
        return HttpResponseRedirect(reverse('userApp:profile'))

    data = {
        "user_single": user_single,
        "already_followed": already_followed,
    }
    return render(request, 'userApp/single_user.html', data)


@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        followed_user = Follow(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('userApp:search_Single_user', kwargs={'username': username}))


@login_required
def unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('userApp:search_Single_user', kwargs={'username': username}))

templates/userApp/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{ title }} | Social Site {% endblock title %}
{% block stylelink %} {% endblock stylelink %}
{% block inlineStyle %}
    <style>
    .sing_up{
        width:550px;
        border: 1px solid #ccc;
        padding: 20px 30px
    }
    .log_in{
        width:550px;
        border: 1px solid #ccc;
        padding: 20px 30px
    }
    .bg-dark {
    background-color: #3b5998!important;
    }
    .dropdown-menu {

    background-color: #3b5998;
    }
    </style>
{% endblock inlineStyle %}

{% block navbar %}
     {% include 'navbar2.html' %}
{% endblock navbar %}

{% block main_contain %}
     <center>
        <div class="log_in" >
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" style="width: 100%;" class="btn btn-primary">Log in </button>
            </form>
        </div>

       <div class="sing_up">
           <p>Don't have account? <a href="{% url 'userApp:sing_up' %}">Sing up </a></p>
       </div>
    </center>
{% endblock main_contain %}

{% block javascriptLink %} {% endblock javascriptLink %}
{% block inlinejavascriptLink %} {% endblock inlinejavascriptLink %}

templates/userApp/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | Social Site {% endblock title %}
{% block stylelink %} {% endblock stylelink %}
{% block inlineStyle %}
    <style>
    .crop{
        width:200px;
        height:200px;
        overflow:hidden;

    }
    .crop img{
        width:400px;
        height:400px;
        margin:-75px 0 0 -100px;

    }
    .bg-dark {
    background-color: #3b5998!important;
    }
    .dropdown-menu {

    background-color: #3b5998;
    }
    </style>

{% endblock inlineStyle %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block main_contain %}
    <div>
        <div class="row">
            <div class="col-sm-4">
                {% if user.user_profile.profile_pic %}
                 <img src="{{ user.user_profile.profile_pic.url }}" class="rounded-circle" width="250px" height="250px" alt="img not found">
                {% else %}
                   <img src="/media/default_pic.png" class="rounded-circle" width="250px" height="250px" alt="img not found">
                {% endif %}
            </div>
            <div class="col-sm-8">
                <h3>{{ user.username }} &nbsp; <a href="{% url 'userApp:ProfileEdit' %}">Profile Edit</a></h3>
                <br>
                <h4>{{ user.post.count}} Posts &nbsp; &nbsp; {{ user.follower.count }} Following &nbsp; &nbsp; {{ user.following.count }} Follower </h4>
                <br>
                <h4>{{ user.user_profile.full_name  }}</h4> <!-- user_profile related name model er UserProfile-->
                <h6>{{ user.user_profile.description|linebreaks }}</h6> <!-- user_profile related name model er UserProfile-->
            </div>
        </div>
    </div>
    <hr>
    <!-- Button to Open the Modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Post
</button>

<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Create New Post </h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <form  method="POST"  enctype="multipart/form-data">
                {{ form|crispy }}
                  {% csrf_token %}

               <button type="submit" style="width: 100%;" class="btn btn-primary">Send </button>

          </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger" data-dismiss="modal">cancel</button>
      </div>

    </div>
  </div>
</div>
<br>
<br>
    <!-- show all post -->
    <div class="row">
    {% for p in user.post.all %}
        <div class="crop">
            <img src="{{ p.image.url }}" alt="Img not found" title="{{ p.caption }}">
        </div>
    {% endfor %}
    </div>



{% endblock main_contain %}

{% block javascriptLink %} {% endblock javascriptLink %}
{% block inlinejavascriptLink %} {% endblock inlinejavascriptLink %}

templates/userApp/profile_Edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | Social Site {% endblock title %}
{% block stylelink %} {% endblock stylelink %}
{% block inlineStyle %}
    <style>
     .bg-dark {
    background-color: #3b5998!important;
    }
    </style>
{% endblock inlineStyle %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock navbar %}

{% block main_contain %}
    <div class="profile_Edit" >
            <form action="" method="post" enctype="multipart/form-data">
               {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" style="width: 100%;" class="btn btn-primary">Edit Profile</button>
            </form>
        </div>
{% endblock main_contain %}

{% block javascriptLink %} {% endblock javascriptLink %}
{% block inlinejavascriptLink %} {% endblock inlinejavascriptLink %}

templates/userApp/sing_up.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} {{ title }}| Social Site {% endblock title %}
{% block stylelink %} {% endblock stylelink %}
{% block inlineStyle %}
    <style>
    .sing_up{
        width:450px;
        border: 1px solid #ccc;
        padding: 20px 30px
    }
    .log_in{
        width:450px;
        border: 1px solid #ccc;
        padding: 20px 30px
    }
     .bg-dark {
    background-color: #3b5998!important;
    }
    .dropdown-menu {

    background-color: #3b5998;
    }
    </style>
{% endblock inlineStyle %}

{% block navbar %}
 {% include 'navbar2.html' %}
{% endblock navbar %}

{% block main_contain %}
    <div class="row">
    <div class="col-sm-5 mt-5">
     <img src="{% static 'myfile/images/facebook_background.png' %}" style="width:90%;" alt="Img not found">
    </div>
    <div class="col-sm-7">
            <center>
        <div class="sing_up" >
            <h3>Create an account .</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" style="width: 100%;" class="btn btn-primary">Sing Up</button>
            </form>
        </div>

       <div class="log_in">
           <p>Have an account? <a href="{% url 'userApp:login' %}">Log in</a></p>
       </div>
    </center>
    </div>
    </div>


    <footer class="p-2">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-sm-12">
            <ul class="list-inline">
              <li class="list-inline-item"><a href="#">English (US)</a></li>
              <li class="list-inline-item"><a href="#">Español</a></li>
              <li class="list-inline-item"><a href="#">Français (France)</a></li>
              <li class="list-inline-item"><a href="#">中文(简体)</a></li>
              <li class="list-inline-item"><a href="#">العربية</a></li>
              <li class="list-inline-item"><a href="#">Português (Brasil)</a></li>
              <li class="list-inline-item"><a href="#">Italiano</a></li>
              <li class="list-inline-item"><a href="#">한국어</a></li>
              <li class="list-inline-item"><a href="#">Deutsch</a></li>
              <li class="list-inline-item"><a href="#">हिन्दी</a></li>
              <li class="list-inline-item"><a href="#">日本語</a></li>
              <li class="list-inline-item">
                <a href="#" class="btn-secondary btn-add-language">
                  <i class="fas fa-plus fa-1x text-white"></i>
                </a>
              </li>
            </ul>
            <hr>
            <ul class="list-inline">
              <li class="list-inline-item"><a href="#">Sign Up</a></li>
              <li class="list-inline-item"><a href="#">Log In</a></li>
              <li class="list-inline-item"><a href="#">Messenger</a></li>
              <li class="list-inline-item"><a href="#">Facebook Lite</a></li>
              <li class="list-inline-item"><a href="#">Watch</a></li>
              <li class="list-inline-item"><a href="#">People</a></li>
              <li class="list-inline-item"><a href="#">Profiles</a></li>
              <li class="list-inline-item"><a href="#">Pages</a></li>
              <li class="list-inline-item"><a href="#">Pages Categories</a></li>
              <li class="list-inline-item"><a href="#">Events</a></li>
              <li class="list-inline-item"><a href="#">Places</a></li>
              <li class="list-inline-item"><a href="#">Games</a></li>
              <li class="list-inline-item"><a href="#">Locations</a></li>
              <li class="list-inline-item"><a href="#">Marketplace</a></li>
              <li class="list-inline-item"><a href="#">Groups</a></li>
              <li class="list-inline-item"><a href="#">Instagram</a></li>
              <li class="list-inline-item"><a href="#">Local</a></li>
              <li class="list-inline-item"><a href="#">Fundraisers</a></li>
              <li class="list-inline-item"><a href="#">Services</a></li>
              <li class="list-inline-item"><a href="#">About</a></li>
              <li class="list-inline-item"><a href="#">Create Ad</a></li>
              <li class="list-inline-item"><a href="#">Create Page</a></li>
              <li class="list-inline-item"><a href="#">Developers</a></li>
              <li class="list-inline-item"><a href="#">Careers</a></li>
              <li class="list-inline-item"><a href="#">Privacy</a></li>
              <li class="list-inline-item"><a href="#">Cookies</a></li>
              <li class="list-inline-item"><a href="#">Cookies</a></li>
              <li class="list-inline-item"><a href="#">Ad Choices <i class="fas fa-ad"></i></a></li>
              <li class="list-inline-item"><a href="#">Terms</a></li>
              <li class="list-inline-item"><a href="#">Account Security</a></li>
              <li class="list-inline-item"><a href="#">Login Help</a></li>
              <li class="list-inline-item"><a href="#">Help</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>




{% endblock main_contain %}

{% block javascriptLink %} {% endblock javascriptLink %}
{% block inlinejavascriptLink %} {% endblock inlinejavascriptLink %}

templates/userApp/single_user.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | Social Site {% endblock title %}
{% block stylelink %} {% endblock stylelink %}
{% block inlineStyle %}
    <style>
    .crop{
        width:200px;
        height:200px;
        overflow:hidden;

    }
    .crop img{
        width:400px;
        height:400px;
        margin:-75px 0 0 -100px;

    }
    </style>

{% endblock inlineStyle %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block main_contain %}
    <div>
        <div class="row">
            <div class="col-sm-4">
                {% if user_single.user_profile.profile_pic %}
                 <img src="{{ user_single.user_profile.profile_pic.url }}" class="rounded-circle" width="250px" height="250px" alt="img not found">
                {% else %}
                   <img src="/media/default_pic.png" class="rounded-circle" width="250px" height="250px" alt="img not found">
                {% endif %}
            </div>
            <div class="col-sm-8">
                <h3>{{ user_single.username }} &nbsp; </h3>
                    {% if not already_followed %}
                     <a href="{% url 'userApp:followed' username=user_single.username %}" class="btn btn-primary">Following </a>
                     {% else %}
                     <a href="{% url 'userApp:unfollow' username=user_single.username %}" class="btn btn-primary">Unfollow </a>
                     {% endif %}

                <br>
                <h4>{{ user_single.post.count}} Posts &nbsp; &nbsp; {{ user_single.follower.count }} Following &nbsp; &nbsp; {{ user_single.following.count }} Follower </h4>
                <br>
                <h4>{{ user_single.user_profile.full_name  }}</h4> <!-- user_profile related name model er UserProfile-->
                <h6>{{ user_single.user_profile.description|linebreaks }}</h6> <!-- user_profile related name model er UserProfile-->
            </div>
        </div>
    </div>
    <hr>

<br>
<br>
    <!-- show all post -->
    <div class="row">
    {% for p in user_single.post.all %}
        <div class="crop">
            <img src="{{ p.image.url }}" alt="Img not found" title="{{ p.caption }}">
        </div>
    {% endfor %}
    </div>



{% endblock main_contain %}

{% block javascriptLink %} {% endblock javascriptLink %}
{% block inlinejavascriptLink %} {% endblock inlinejavascriptLink %}