App_post/urls.py
from django.urls import path
from .import views
app_name = 'App_post'
urlpatterns = [
       path('',views.Homepage,name='homepage'),
       path('like/<pk>/',views.liked,name='liked'),
       path('unlike/<pk>/',views.unliked,name='unliked'),
    ]

Social_site_project/urls.py
"""Social_site_project URL Configuration
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from App_post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('userApp.urls')),
    path('post/',include('App_post.urls')),
    path('',views.Homepage,name='homepage'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userApp/urls.py
from django.urls import path
from .import views
app_name = 'userApp'
urlpatterns = [
    path('sing_up/',views.Sing_up,name='sing_up'),
    path('login/',views.login_page,name='login'),
    path('Logout/',views.Log_out,name='Logout'),
    path('ProfileEdit/',views.P_Edit_page,name='ProfileEdit'),
    path('profile/',views.view_profile,name='profile'),
    path('s_single_user/<username>/',views.Single_user,name='search_Single_user'),
    path('followed/<username>/',views.follow,name='followed'),
    path('unfollow/<username>/',views.unfollow,name='unfollow'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <!-- Fontawesome  -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/duotone.css" integrity="sha384-R3QzTxyukP03CMqKFe0ssp5wUvBPEyy9ZspCB+Y01fEjhMwcXixTyeot+S40+AjZ" crossorigin="anonymous"/>
   <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/fontawesome.css" integrity="sha384-eHoocPgXsiuZh+Yy6+7DsKAerLXyJmu2Hadh4QYyt+8v86geixVYwFqUvMU8X90l" crossorigin="anonymous"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'extendFile/css/bootstrap.min.css' %}">
    {% block stylesheet_link %}
    {% endblock %}
    <title> {% block title %}{% endblock %} </title>
      {% block stylelink %} {% endblock stylelink %}
      {% block inlineStyle %} {% endblock inlineStyle %}

  </head>
  <body>

  {% block navbar %}
  {% endblock navbar %}
<div class="container" style="padding-top:20px;">
  {% block main_contain %}
  {% endblock main_contain %}
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'extendFile/js/jQuery_v3.6.0.js' %}"  ></script>
    <script src="{% static 'extendFile/js/popper.min.js'%}" ></script>
    <script src="{% static 'extendFile/js/bootstrap.min.js' %}" ></script>

    <script src="{% static 'myFile/js/myJquery.js' %}" ></script>

{% block javascriptLink %} {% endblock javascriptLink %}
{% block inlinejavascriptLink %} {% endblock inlinejavascriptLink %}

  </body>
</html>

templates/navbar.html
  {% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href=""><img src="{% static 'myfile/images/facebook.png' %}" style="width:100px;height:50px"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
       <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'App_post:homepage' %}">Home <span class="sr-only">(current)</span></a>
      </li> &nbsp; &nbsp;  &nbsp; &nbsp;
      <form class="form-inline" action="" method="get">
        <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search">
        <button class="btn btn-success" type="submit">Search</button>
      </form>
    </ul>
      <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
              <li class="nav-item dropdown">

                  {% if user.user_profile.profile_pic %}
                      <a class="nav-link " href="" id="navbarDropdown" role="button" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false"><img
                              src="{{ user.user_profile.profile_pic.url }}" class="rounded-circle" width="40px"
                              height="40px" class="rounded-circle" alt="img not Found"> </a>
                  {% else %}
                      <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false"><img src="/media/default_pic.png"
                                                                                  class="rounded-circle" width="75px"
                                                                                  height="75px" alt="img not Found">
                      </a>
                  {% endif %}
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="nav-link" href="{% url 'userApp:Logout' %}">Logout</a>
                      <a class="nav-link" href="{% url 'userApp:profile' %}">Profile View</a>
                  </div>
              </li>


          {% else %}
            <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                      Dropdown
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="nav-link" href="{% url 'userApp:login' %}">Login</a>
                       <a class="nav-link" href="{% url 'userApp:sing_up' %}">SignUp</a>

                  </div>
              </li>

          {% endif %}
      </ul>
  </div>
  </nav>

templates/navbar2.html
 {% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href=""><img src="{% static 'myfile/images/facebook.png' %}" style="width:100px;height:50px"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
       <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'App_post:homepage' %}">Facebook <span class="sr-only">(current)</span></a>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
        <form class="float-right">
            <div class="form-row">
              <div class="col-auto">
                <label class="sr-only" for="emailPhone">Email or Phone</label>
                <input type="text" class="form-control form-control-sm mb-2" id="emailPhone" placeholder="Email or Phone">
              </div>
              <div class="col-auto">
                <label class="sr-only" for="password">Password</label>
                <div class="input-group mb-2">
                  <input type="text" class="form-control form-control-sm" id="password" placeholder="Password">
                </div>
              </div>
              <div class="col-auto">
                <input type="submit" id="submit" class="btn btn-sm btn-fb mb-2 align-bottom" value="Log In">
              </div>
            </div>
          </form>

        <li class="nav-item dropdown">

            {% if user.user_profile.profile_pic %}
                <a class="nav-link " href="" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false"><img
                        src="{{ user.user_profile.profile_pic.url }}" class="rounded-circle" width="40px"
                        height="40px" class="rounded-circle" alt="img not Found"> </a>
            {% else %}
                <a class="nav-link " href="" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false"><img src="/media/auto_pic_r/default_pic.png"
                                                                   class="rounded-circle" width="75px"
                                                                   height="75px" alt="img not Found">
                </a>
            {% endif %}
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="nav-link" href="{% url 'userApp:login' %}">Login</a>
             <a class="nav-link" href="{% url 'userApp:sing_up' %}">SignUp</a>

            </div>
        </li>


    </ul>
  </div>
  </nav>

templates/sample.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ title }} | Social Site {% endblock title %}
{% block stylelink %} {% endblock stylelink %}
{% block inlineStyle %} {% endblock inlineStyle %}

{% block navbar %}
{% endblock navbar %}

{% block main_contain %}
{% endblock main_contain %}

{% block javascriptLink %} {% endblock javascriptLink %}
{% block inlinejavascriptLink %} {% endblock inlinejavascriptLink %}