App_post/urls.py
from django.urls import path
from .import views
app_name = 'App_post'
urlpatterns = [
       path('',views.Homepage,name='homepage'),
       path('like/<pk>/',views.liked,name='liked'),
       path('unlike/<pk>/',views.unliked,name='unliked'),
    ]

Social_site_project/urls.py
"""Social_site_project URL Configuration
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from App_post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('userApp.urls')),
    path('post/',include('App_post.urls')),
    path('',views.Homepage,name='homepage'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userApp/urls.py
from django.urls import path
from .import views
app_name = 'userApp'
urlpatterns = [
    path('sing_up/',views.Sing_up,name='sing_up'),
    path('login/',views.login_page,name='login'),
    path('Logout/',views.Log_out,name='Logout'),
    path('ProfileEdit/',views.P_Edit_page,name='ProfileEdit'),
    path('profile/',views.view_profile,name='profile'),
    path('s_single_user/<username>/',views.Single_user,name='search_Single_user'),
    path('followed/<username>/',views.follow,name='followed'),
    path('unfollow/<username>/',views.unfollow,name='unfollow'),
]

App_post/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=264, blank=True)
    upload_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.caption

    class Meta:
        ordering = ['-upload_date']


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='like_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

App_post/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'caption', ]

App_post/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from userApp.models import Follow
from App_post.models import Post, Like
from django.urls import reverse


# Create your views here.
@login_required
def Homepage(request):
    following_list = Follow.objects.filter(follower=request.user)
    post_show = Post.objects.filter(author__in=following_list.values_list('following'))
    like_post = Like.objects.filter(user=request.user)
    like_post_list = like_post.values_list('post', flat=True)

    if request.method == 'GET':
        search = request.GET.get('search', '')
        results = User.objects.filter(username__icontains=search)

    data = {
        "title": 'Home Page',
        "results": results,
        "search": search,
        "post_show": post_show,
        "like_post_list": like_post_list,
    }
    return render(request, 'app_post/index.html', data)


@login_required
def liked(request, pk):
    post = Post.objects.get(pk=pk)
    already_like = Like.objects.filter(post=post, user=request.user)
    if not already_like:
        like_post = Like(post=post, user=request.user)
        like_post.save()
    return HttpResponseRedirect(reverse('App_post:homepage'))


@login_required
def unliked(request, pk):
    post = Post.objects.get(pk=pk)
    already_like = Like.objects.filter(post=post, user=request.user)
    already_like.delete()
    return HttpResponseRedirect(reverse('App_post:homepage'))

templates/app_post/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ title }} | Social Site {% endblock title %}
{% block stylelink %} {% endblock stylelink %}
{% block inlineStyle %}
    <style>
    .bg-dark {
    background-color: #3b5998!important;
    }
    .dropdown-menu {

    background-color: #3b5998;
    }
    </style>
{% endblock inlineStyle %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock navbar %}

{% block main_contain %}
    {% if search %}
        {% for r in results %}
            <div class="row">
                <div class="col-sm-2">
                    {% if user.user_profile.profile_pic %}
                        <img src="{{ r.user_profile.profile_pic.url }}" style="width:75px; height:75px;"
                             class="rounded-circle"
                             alt="Img Not Found"> <br>
                    {% else %}
                        <img src="/media/auto_pic_r/default_pic.png" style="width:75px; height:75px;"
                             class="rounded-circle"
                             alt="Img Not Found"> <br>

                    {% endif %}
                </div>
                <div class="col-sm-10">
                    <a href="{% url 'userApp:search_Single_user' username=r.username %}">  {{ r.username }}</a>
                    <br>
                    {{ r.user_profile.full_name }}
                </div>
            </div>
        {% endfor %}
        <!--show post in Home page-->
    {% else %}
        <div class="row">
            <div class="col-sm-8">
                {% for po in post_show %} <!--following and post related-name model-->
                    <div style="border:1px solid #888888;">
                        <div style="padding:10px;">
                            {% if po.author.user_profile.profile_pic %}
                                <img src="{{ user.user_profile.profile_pic.url }}" style="width:40px; height:40px;"
                                     class="rounded-circle" alt="Img Not Found">
                            {% else %}
                                <img src="/media/auto_pic_r/default_pic.png" class="rounded-circle" width="40px"
                                     height="40px"
                                     alt="img d not Found">
                            {% endif %}
                            <a href="{% url 'userApp:search_Single_user' username=po.author %}">{{ po.author }}</a>
                        </div>
                        <img src="{{ po.image.url }}" width="100%;" alt="image not found" style="max-height: 370px;">
                        <div class="row">
                        <div style="padding:20px;">
                            {{ po.like_post.count }}Likes <br>
                            {% if po.pk in like_post_list %}
                                <a href="{% url 'App_post:unliked' pk=po.pk %}"><i class="far fa-thumbs-up fa-2px"></i></a>
                            {% else %}
                                <a href="{% url 'App_post:liked' pk=po.pk %}"><i class="fas fa-thumbs-up"></i></a>
                            {% endif %}
                        </div>
                       <div style="padding:20px ;" class="ml-auto">
                           <a>Comment</a>
                       </div>
                    </div>
                    </div>
                    <br>
                {% endfor %}
            </div>
            <div class="col-sm-4">
                <div class="row">
                    <div class="col-sm-4">
                        {% if user.user_profile.profile_pic %}
                            <img src="{{ user.user_profile.profile_pic.url }}" style="width:75px; height:75px;"
                                 class="rounded-circle"
                                 alt="Img Not Found"> <br>
                        {% else %}
                            <img src="/media/auto_pic_r/default_pic.png" style="width:75px; height:75px;"
                                 class="rounded-circle"
                                 alt="Img Not Found"> <br>

                        {% endif %}
                    </div>
                    <div class="col-sm-8">
                        <a href="{% url 'userApp:search_Single_user' username=user.username %}">  {{ user.username }}</a>
                        <br>
                        <a>  {{ user.user_profile.full_name }}</a>
                    </div>
                </div>
            </div>
        </div>

        <!--show post in Home page-->

    {% endif %}
{% endblock main_contain %}

{% block javascriptLink %} {% endblock javascriptLink %}
{% block inlinejavascriptLink %} {% endblock inlinejavascriptLink %}